version: "2"

issues:
  max-same-issues: 50

formatters:
  enable:
    - goimports
    - golines
  settings:
    goimports:
      local-prefixes:
        - github.com/srunas/effective-mobile
    golines:
      max-len: 120

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - fatcontext
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - predeclared
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace

  settings:
    cyclop:
      max-complexity: 15
      package-average: 10.0

    errcheck:
      check-type-assertions: true

    funlen:
      lines: 80
      statements: 50

    gocognit:
      min-complexity: 20

    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false

    govet:
      enable-all: true
      disable:
        - fieldalignment
      settings:
        shadow:
          strict: true

    mnd:
      ignored-functions:
        - os.Chmod
        - os.Mkdir.*
        - os.OpenFile
        - os.WriteFile

    nakedret:
      max-func-lines: 0

    nolintlint:
      allow-no-explanation: [funlen, gocognit, golines]
      require-explanation: true
      require-specific: true

    perfsprint:
      strconcat: false

    reassign:
      patterns:
        - ".*"

    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx

    sloglint:
      no-global: ""
      context: scope

    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1016
        - -QF1008
        - -ST1003

    revive:
      rules:
        - name: var-naming
          disabled: true

  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - source: 'TODO'
        linters: [godot]
      - source: '// @'
        linters: [godot, staticcheck]
      - text: 'should have a package comment'
        linters: [revive]
      - text: 'exported \S+ \S+ should have comment( \(or a comment on this block\))? or be unexported'
        linters: [revive]
      - path: '_test\.go'
        linters:
          - bodyclose
          - dupl
          - errcheck
          - funlen
          - goconst
          - gosec
          - noctx
      - path: 'docs/'
        linters:
          - gochecknoglobals
          - goconst
          - godot
          - mnd
      - path: 'internal/infrastructure/repository/subscription-repository/sqlcgen/'
        linters:
          - gochecknoglobals
          - goconst
          - mnd
          - godot
