services:
  postgres:
    image: postgres:16-alpine
    container_name: effective-mobile-postgres
    environment:
      POSTGRES_DB: effective_mobile
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d effective_mobile"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: effective-mobile-app
    ports:
      - "8080:8080"
    volumes:
      - ./internal/config/config.docker.yaml:/app/internal/config/config.yaml
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data: