// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const calculateTotal = `-- name: CalculateTotal :one
SELECT COALESCE(SUM(price), 0)::bigint AS total
FROM subscriptions
WHERE ($1::text = '' OR user_id = $1)
  AND ($2::text = '' OR service_name = $2)
  AND start_date >= $3
  AND start_date <= $4
`

type CalculateTotalParams struct {
	Column1     string    `json:"column_1"`
	Column2     string    `json:"column_2"`
	StartDate   time.Time `json:"start_date"`
	StartDate_2 time.Time `json:"start_date_2"`
}

func (q *Queries) CalculateTotal(ctx context.Context, arg CalculateTotalParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, calculateTotal,
		arg.Column1,
		arg.Column2,
		arg.StartDate,
		arg.StartDate_2,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createSubscription = `-- name: CreateSubscription :exec
INSERT INTO subscriptions (id, service_name, price, user_id,
                           start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSubscriptionParams struct {
	ID          string       `json:"id"`
	ServiceName string       `json:"service_name"`
	Price       int64        `json:"price"`
	UserID      string       `json:"user_id"`
	StartDate   time.Time    `json:"start_date"`
	EndDate     sql.NullTime `json:"end_date"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, createSubscription,
		arg.ID,
		arg.ServiceName,
		arg.Price,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions
WHERE id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSubscription, id)
	return err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, service_name, price, user_id, start_date, end_date,
       created_at, updated_at
FROM subscriptions
WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id string) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, service_name, price, user_id, start_date, end_date,
       created_at, updated_at
FROM subscriptions
WHERE ($1::text = '' OR user_id = $1)
ORDER BY created_at DESC
`

func (q *Queries) ListSubscriptions(ctx context.Context, dollar_1 string) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.Price,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :exec
UPDATE subscriptions
SET service_name = $2,
    price        = $3,
    start_date   = $4,
    end_date     = $5,
    updated_at   = NOW()
WHERE id = $1
`

type UpdateSubscriptionParams struct {
	ID          string       `json:"id"`
	ServiceName string       `json:"service_name"`
	Price       int64        `json:"price"`
	StartDate   time.Time    `json:"start_date"`
	EndDate     sql.NullTime `json:"end_date"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateSubscription,
		arg.ID,
		arg.ServiceName,
		arg.Price,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}
