// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	CalculateTotal(ctx context.Context, arg CalculateTotalParams) (int64, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error
	DeleteSubscription(ctx context.Context, id string) error
	GetSubscriptionByID(ctx context.Context, id string) (Subscription, error)
	ListSubscriptions(ctx context.Context, dollar_1 string) ([]Subscription, error)
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error
}

var _ Querier = (*Queries)(nil)
